name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install the Rust toolchain for WebAssembly
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      # Install Trunk for building Yew projects
      - name: Install Trunk
        run: cargo install trunk

      # Build the project using trunk with the correct public URL
      - name: Build project
        run: trunk build --release --public-url /${{ github.repository_owner }}/

      # Deploy the build to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
